simplesocial/posts/urls.py
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(), name="all"),
    path("new/",views.CreatePost.as_view(), name ="create"),
    path("by/<username>/",views.UserPosts.as_view(), name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(), name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name ='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    # Auth app is default in Django but the path is not included in the route so we have to add auth path to project’s urls.py.
    path('accounts/',include('django.contrib.auth.urls')),# it allows us to load up the user auth features
    path('test/', views.TestPage.as_view(),name ='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('posts/',include("posts.urls",namespace="posts")),
    path('groups/',include("groups.urls",namespace="groups")),
]

simplesocial/posts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
# Create your models here.
# POSTS MODELS.py
import misaka

from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User, related_name="posts",on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html=models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name="posts", null =True, blank=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.message

    def save(self,*args,**kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse(
            "posts:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk
            }
        )

    class Meta:
        ordering = ["-created_at"]
        unique_together=["user","message"]

simplesocial/posts/forms.py
from django import forms
from . import models


class PostForm(forms.ModelForm):
    class Meta:
        fields = ("message", "group")
        model = models.Post

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None) # if user defined user is "user" else user = null
        super().__init__(*args, **kwargs) #https://www.udemy.com/course/python-and-django-full-stack-web-developer-bootcamp/learn/lecture/7133898#questions/3910688
        if user is not None:
            self.fields["group"].queryset = models.Group.objects.filter(members = user)

# models.Group.objects.filter(
#     pk__in=user.groups.values_list("group__pk") not working

simplesocial/posts/views.py
from django.shortcuts import render
from django.http import Http404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages
# Create your views here.
# SelectRelatedMixin
# A simple mixin which allows you to specify a list or tuple of foreign key fields to perform a select_related on
# pip install django-braces
from braces.views import SelectRelatedMixin
from django.views import generic # call CRUD

from . import forms
from . import models
# Don't forget to import the model
from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()

class PostList(SelectRelatedMixin,generic.ListView):
    model = models.Post
    select_related = ('user','group') # If you don't set the select_related class attribute it ultimately has not effect on the class.
    queryset=models.Post.objects.all()

    def get_context_data(self, **kwargs):

         context = super(PostList, self).get_context_data(**kwargs)
         context['user_groups'] = Group.objects.filter(members__in=[self.request.user])
         context['all_groups'] = Group.objects.all()
         return context

class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'
#  3 method get data: get,get_queryset, get_context_data () important()
    def get_queryset(self):
        try:
            # Tim bai "Tối ưu hóa queryset với select_related và prefetch_related"
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username") # And then we're going to get the user name is exactly equal to the user name of whatever is user logged
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return   self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context

class PostDetail(SelectRelatedMixin,generic.DetailView):
    model = models.Post
    select_related = ("user","group")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username") # note: Do not use request.user without login check
        )
#  question: How come CreatePost in SimpleSocial has form_valid function but CreatePost in blog doesn't? They both have a user associated with it. And there isn't anything else being done in form_valid function in SimpleSocial.
# answer This is really a question of design. They are just different approaches to similar issues and neither of them is right nor wrong. In the Blog project when we create a post we have to manually select a value for the  author field. In the SimpleSocial project by adding the form_valid method we set the author (now called user) to a property from the incoming request so that user is always set to whoever is actually creating the post.
class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    form_class = forms.PostForm
    # fields = ('message','group')
    model = models.Post
    # fields["group"].queryset = models.Group.objects.filter(members = object.user)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin,SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ('user','group')
    success_url = reverse_lazy("posts:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self,*args,**kwargs):
        messages.success(self.request,"post deleted")
        return super().delete(*args,**kwargs)

simplesocial/posts/templates/posts/_post.html
<div class="media">
	<h3 class="mr-5"><a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a></h3>

	<div class="media-body">
		<strong>{{ post.user.username }}</strong>
		<h5>{{ post.message_html|safe }}</h5>
			<time class="time"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a></time>
			{% if post.group %}
			<span class="group-name">in <a href="#">{{ post.group.name }}</a></span>
			{% endif %}
		</h5>

		<div class="media-footer">
			{% if user.is_authenticated and post.user == user and not hide_delete %}
				<a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
					<span class="fa fa-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">Delete</span>
				</a>
			{% endif %}
		</div>
	</div>
</div>

simplesocial/posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}
<div class="posts-page">
	<div class="container">
		{% block prepost %}{% endblock %}
		{% block post_content %}{% endblock %}
		{% block post_post %}{% endblock %}
	</div>
</div>
{% endblock %}

simplesocial/posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<h3>Are you sure you want to delete this post?</h3>

<div class="posts">
	{% include "posts/_post.html" with post=object hide_delete=True %} {# ??? with is not nessesary#}
</div>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-light btn-large">Cancel</a>
</form>

{% endblock %}
{# NoReverseMatch at /posts/delete/2/ modifie username= user.username #}

simplesocial/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<!-- <div class="col-md-8"> -->
    {% include "posts/_post.html" %}
<!-- </div> -->
{% endblock %}

simplesocial/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap4 %}

{% block post_content %}
<h4>Create New Post</h4>
{# The current path, posts/new/{url 'posts:create'}, didn't match any of these. it have not %% in urls #}
<form method="POST" action="{% url 'posts:create' %}" id="postForm">
	{% csrf_token %}
	{% bootstrap_form form %}
	{% buttons %}
		<button type="submit" class="btn btn-primary btn-large">Post</button>
	{% endbuttons %}
</form>
{% endblock %}

simplesocial/posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}
{% load humanize %} {# Un ensemble de filtres de gabarits fournis par Django et utiles pour ajouter une « touche humaine » aux données.#}

{% block pre_post_content %}
<div class="col-md-4">
	{% if request.user.is_authenticated %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">Your Groups</h5>
			<ul class="list-unstyled">

				{% for member_group in get_user_groups %}
				<li class="group li-with-bullet">
					<a href="{% url 'groups:single' slug=member_group.group.slug %}">{{ member_group.group.name }}</a>
				</li>
				{% endfor %}

			</ul>
		</div>
	</div>
	{% endif %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">All groups</h5>
			<ul class="list-unstyled">
				{# {% get_other_groups as other_groups %} #}
				{% for other_group in get_other_groups %}
					<li class="group li-with-bullet"><a href="{% url 'groups:single' slug=other_group.slug %}">{{ other_group.name }}</a></li>
				{% endfor %}
			</ul>

		</div>
	</div>
</div>
{% endblock %}
{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
  {% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}

simplesocial/posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
<div class="col-md-4">
	<h1>@{{ post_user.username }}</h1>
	<p>Post History</p>
</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
		{% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}