simplesocial/groups/urls.py
# GROUPS URLS.PY
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns =[
    path('', views.ListGroup.as_view(), name ='all'),
    path('new/',views.CreateGroup.as_view(), name ='create'),
    path('posts/in/<slug>', views.SingleGroup.as_view(), name ="single"),
    path("join/<slug>/",views.JoinGroup.as_view(),name="join"),
    path("leave/<slug>/",views.LeaveGroup.as_view(),name="leave"),


]

simplesocial/posts/urls.py
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(), name="all"),
    path("new/",views.CreatePost.as_view(), name ="create"),
    path("by/<username>/",views.UserPosts.as_view(), name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(), name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name ='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    # Auth app is default in Django but the path is not included in the route so we have to add auth path to project’s urls.py.
    path('accounts/',include('django.contrib.auth.urls')),# it allows us to load up the user auth features
    path('test/', views.TestPage.as_view(),name ='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('posts/',include("posts.urls",namespace="posts")),
    path('groups/',include("groups.urls",namespace="groups")),
]

simplesocial/groups/models.py
from django.db import models
from django.utils.text import slugify
# from django.conf import settings #?
from django.urls import reverse
# Create your models here.
# installing the c++ Compiler for python with this command:
# conda install libpython m2w64-toolchain -c msys2
# pip install misaka
import misaka # It features a fast HTML renderer and functionality to make custom renderers

from django.contrib.auth import get_user_model # call User's model of Django
User = get_user_model()

# https://docs.djangoproject.com/en/2.0/howto/custom-template-tags/#inclusion-tags
# This is for the in_group_members check template tag
#https://openclassrooms.com/fr/courses/1871271-developpez-votre-site-web-avec-le-framework-django/1873273-simplifions-nos-templates-filtres-tags-et-contextes
from django import template
register = template.Library() #?? custom template may be <p class="mb-1">{{ group.description_html|safe }}</p>

class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default ='')
    description_html = models.TextField(editable=False, blank=True, default='')
    members = models.ManyToManyField(User,through="GroupMember") # Ajout member here when relationship m2m, why not ajout this in Model "User", but is complicated

    def __str__(self):
        return self.name
# Overriding predefined model methods
# model có nhiều các method được dựng sẵn của Django và trong đó hiển nhiên sẽ có các method là sự thể hiện các hành vi vơi cơ sở dữ liệu. Thông thường thì chúng ta sẽ muốn tùy chỉnh các hành vi save() hay delete()
#
# Và đương nhiên là chũng ta hoàn toàn có thể làm được điều này bằng cách override lại chính method đó. Cụ thể như sau:
    def save(self,*args,**kwargs):
        self.slug = slugify(self.name) #sesion previous
        self.description_html =misaka.html(self.description)
        super().save(*args,**kwargs) # Call the "real" save() method.

    def get_absolute_url(self): #method này cho phép Django có thể biết được cách biết được URL cho từng object. Mặc định thf Django sẽ sử dụng nó trong admin interface
        return reverse('groups:single',kwargs={'slug': self.slug})

    class Meta:
        ordering   = ['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name='memberships',on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name='user_groups', on_delete = models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together =("group","user")
#############################################
#         test for understanding
# python manage.py shell
# from groups.models import Group,GroupMember
#  print(Group.objects.all())
#  group1=Group.objects.get(name="Google3")
#  group1.members

simplesocial/groups/views.py
# from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)
from django.views.generic import(TemplateView,ListView,
                                    DetailView,CreateView,UpdateView,DeleteView)
from django.views import generic
from django.urls import reverse
from django.db import IntegrityError
from groups.models import Group, GroupMember
from . import models

# Create your views here.
class CreateGroup(LoginRequiredMixin,CreateView):
    fields = ("name","description")
    model = Group

class SingleGroup(DetailView):
    model = Group
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["one_user"] = self.model.objects.filter(members=1)
    #     return context

class ListGroup(ListView):
    model = Group

class JoinGroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get("slug"))
        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except IntegrityError:
            messages.warning(self.request,("# WARNING: , already a member of {}".format(group.name)))
        else:
            messages.success(self.request,"You are now a member of the {}".format(group.name))
        return super().get(request, *args,**kwargs)

class LeaveGroup(LoginRequiredMixin,generic.RedirectView):
    def get(self,request, *args, **kwargs):
        try:
            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get("slug")
            ).get()

        except models.GroupMember.DoesNotExist:
            messages.warning(
                self.request, "You can't leave this group because you aren't in it"
            )

        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single", kwargs={"slug": self.kwargs.get("slug")})

simplesocial/groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <div class="row">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>  
</div>
{% endblock %}

simplesocial/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}
{% block pregroup %}
<div class="container">
  <h1>{{group.name}}</h1>
  <!-- Sicne group just call group name , attention word group is lowercase singular -->
  <h2>Member Count :{{ group.members.count }}, {{one_user.name}}</h2> {#  les objets QuerySets offrent une méthode count() #}

  <div class="content">
    {% if user in group.members.all %}
      <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-warning"><span class="glyphicon glyphicon-remove-circle"></span>Leave</a>
    {% else %}
      <a href="{% url 'groups:join' slug=group.slug %}"
      class="btn btn-lg btn-fill btn-warning"><span class="fa fa-check-circle-o"></span>Join</a>
    {% endif %}

  </div>
</div>
{% endblock %}
{% block group_content %}
<div class="col-md-8">
  {% if group.posts.count == 0 %}
  <h2>No post in this group yet!</h2>

  {% else %}

    {% for post in group.posts.all %}
      {% include "posts/_post.html" %}
    {% endfor %}

  {% endif %}
</div>
{% endblock %}

simplesocial/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{# why we have to load bootstrap4 here? #}
{% load bootstrap4 %}

{% block group_content %}
<div class="container">
  <h4>Create A New Group</h4>
  <form id="groupForm" action="{% url 'groups:create' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary btn-large">Create</button>
    {% endbuttons %}

  </form>

</div>

{% endblock %}

simplesocial/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="col-md-4">
  <div class="content">
    {% if user.is_authenticated %}
      <h2>Welcom back</h2>
      <a href="{% url 'posts:for_user' username=user.username %}">@{{ user.username }}</a>
    {% endif %}
    <h2>Groups</h2>
    <p>Welcome to the groups Page! <br>Select a Group with a shared interest! </p>
  </div>
  {% if user.is_authenticated %}
    <a href="{% url 'groups:create' %}" class="btn btn-warning" role="button"><span class ="fa fa-plus"></span>Create new group</a>
  {% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
  <div class="list_group">
    {% for group in object_list %}
      <a href="{% url 'groups:single' slug=group.slug %}"
      class="list-group-item list-group-item-action flex-column align-items-start">
        <h3 class="mb-1">{{ group.name }}</h3>
          <p class="mb-1">{{ group.description_html|safe }}</p> {# If you don't want the HTML to be escaped, look at the safe filter and the autoescape tag: off #}
        <div class="d-flex w-40 justify-content-between">
          <small class="text-muted"><span class="badge badge-secondary">{{ group.members.count}}</span>
            member {{ group.members.count|pluralize }}</small>
            <small class ="text-muted"><span class="badge badge-secondary">{{ group.posts.count }}</span>post {{ group.posts.count|pluralize }}
          </small>
          {# ???  for testing #}
        </div>
      </a>
    {% endfor %}

  </div>

</div>

{% endblock %}